#pragma config(Sensor, S1,     UltraSensor,    sensorEV3_Ultrasonic)
#pragma config(Motor,  motorA,          motorLeft,     tmotorEV3_Large, PIDControl, encoder)
#pragma config(Motor,  motorB,          motorRight,    tmotorEV3_Large, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
  // Display instructions for the user
  displayCenteredTextLine(2, "Press up for Code 1");
  displayCenteredTextLine(4, "Press right for Code 2");
  displayCenteredTextLine(6, "Press down for Code 3");

  // Wait for user input
  while (true) {
    if (getButtonPress(buttonUp)) {
      // Code 1
      displayCenteredTextLine(8, "Running Code 1");
      // Insert Code 1 Here

      int distance = 0;
  // Move forward until an obstacle is detected
  while (true)
  {
    distance = getUSDistance(UltraSensor);
    if (distance < 10)
      break;
    setMotorSpeed(motorLeft,24.9999);
    setMotorSpeed(motorRight,24.995);
  }
  // Stop for 5 seconds
  setMotorSpeed(motorLeft, 0);
  setMotorSpeed(motorRight, 0);
  wait1Msec(5000);
  // Reverse for 3 seconds
  setMotorSpeed(motorLeft, -25);
  setMotorSpeed(motorRight, -25);
  wait1Msec(3000);
  // Stop for 2 seconds
  setMotorSpeed(motorLeft, 0);
  setMotorSpeed(motorRight, 0);
  wait1Msec(2000);
  // Turn for 1460 milliseconds
  setMotorSpeed(motorLeft, -25);
  setMotorSpeed(motorRight, 25);
  wait1Msec(1500);
  // Pause for 2 seconds
  setMotorSpeed(motorLeft, 0);
  setMotorSpeed(motorRight, 0);
  wait1Msec(2000);
  // Move forward until an obstacle is detected
  while (true)
  {
    distance = getUSDistance(UltraSensor);
    if (distance < 66)
      break;
    setMotorSpeed(motorLeft, 24.99999);
    setMotorSpeed(motorRight, 24.99995);
  }
  //pause for 2 secs
  setMotorSpeed(motorLeft, 0);
  setMotorSpeed(motorRight, 0);
  wait1Msec(2000);
  // Turn Left for 790 milliseconds
  setMotorSpeed(motorLeft, -25);
  setMotorSpeed(motorRight, 25);
  wait1Msec(790);
  //Stop for 2 seconds
  setMotorSpeed(motorLeft, 0);
  setMotorSpeed(motorRight, 0);
  wait1Msec(2000);
  // Move forward until an obstacle is detected
  while (true)
  {
    distance = getUSDistance(UltraSensor);
    if (distance < 22)
      break;
    setMotorSpeed(motorLeft, 25);
    setMotorSpeed(motorRight, 25);
  }
  //stop for 2 seconds
  setMotorSpeed(motorLeft, 0);
  setMotorSpeed(motorRight, 0);
  wait1Msec(2000);
  // Turn left for 760 milliseconds
  setMotorSpeed(motorLeft, -25);
  setMotorSpeed(motorRight, 25);
  wait1Msec(760);
  //stop for 2 seconds
  setMotorSpeed(motorLeft, 0);
  setMotorSpeed(motorRight, 0);
  wait1Msec(2000);
   // Move forward for 3750 milliseconds
  setMotorSpeed(motorLeft, 25);
  setMotorSpeed(motorRight, 25);
  wait1Msec(3750);
  //stop for 2 seconds
  setMotorSpeed(motorLeft, 0);
  setMotorSpeed(motorRight, 0);
  wait1Msec(2000);
  // Turn left for 790 milliseconds
  setMotorSpeed(motorLeft, -25);
  setMotorSpeed(motorRight, 25);
  wait1Msec(800);
  //stop for 2 seconds
  setMotorSpeed(motorLeft, 0);
  setMotorSpeed(motorRight, 0);
  wait1Msec(2000);
  // Move forward until an obstacle is detected
  while (true)
  {
    distance = getUSDistance(UltraSensor);
    if (distance < 10)
      break;
    setMotorSpeed(motorLeft, 20);
    setMotorSpeed(motorRight, 20);
  }
  // Stop for 5 second
  setMotorSpeed(motorLeft, 0);
  setMotorSpeed(motorRight, 0);
  wait1Msec(5000);
  // Turn around for 1460 milliseconds
  setMotorSpeed(motorLeft, -25);
  setMotorSpeed(motorRight, 25);
  wait1Msec(1460);
  //stop for 2 seconds
  setMotorSpeed(motorLeft, 0);
  setMotorSpeed(motorRight, 0);
  wait1Msec(2000);
  // Move forward until an obstacle is detected
  while (true)
  {
    distance = getUSDistance(UltraSensor);
    if (distance < 22)
      break;
    setMotorSpeed(motorLeft, 20);
    setMotorSpeed(motorRight, 20);
  }
// Stop for 2 second
  setMotorSpeed(motorLeft, 0);
  setMotorSpeed(motorRight, 0);
  wait1Msec(2000);
// Turn right for 750 milliseconds
  setMotorSpeed(motorLeft, 25);
  setMotorSpeed(motorRight, -25);
  wait1Msec(765);
// Stop for 2 second
  setMotorSpeed(motorLeft, 0);
  setMotorSpeed(motorRight, 0);
  wait1Msec(2000);
// Move forward for 3700 milliseconds
  setMotorSpeed(motorLeft, 25);
  setMotorSpeed(motorRight, 25);
  wait1Msec(3700);
// Stop for 2 second
  setMotorSpeed(motorLeft, 0);
  setMotorSpeed(motorRight, 0);
  wait1Msec(2000);
// Turn right for 720 milliseconds
  setMotorSpeed(motorLeft, 25);
  setMotorSpeed(motorRight, -25);
  wait1Msec(765);
// Stop for 2 second
  setMotorSpeed(motorLeft, 0);
  setMotorSpeed(motorRight, 0);
  wait1Msec(2000);
 // Move forward until an obstacle is detected
  while (true)
  {
    distance = getUSDistance(UltraSensor);
    if (distance < 20)
      break;
    setMotorSpeed(motorLeft, 20);
    setMotorSpeed(motorRight, 20);
  }
//stop for 2 seconds
  setMotorSpeed(motorLeft, 0);
  setMotorSpeed(motorRight, 0);
  wait1Msec(2000);
// Turn left for 800 milliseconds
  setMotorSpeed(motorLeft, -25);
  setMotorSpeed(motorRight, 25);
  wait1Msec(780);
// Stop for 2 second
  setMotorSpeed(motorLeft, 0);
  setMotorSpeed(motorRight, 0);
  wait1Msec(2000);
// Move forward until an obstacle is detected
  while (true)
  {
    distance = getUSDistance(UltraSensor);
    if (distance < 10)
      break;
    setMotorSpeed(motorLeft, 25);
    setMotorSpeed(motorRight, 25);
  }
  //stop for 2 seconds
  setMotorSpeed(motorLeft, 0);
  setMotorSpeed(motorRight, 0);
  wait1Msec(2000);
  // Turn for 1400 milliseconds
  setMotorSpeed(motorLeft, -25);
  setMotorSpeed(motorRight, 25);
  wait1Msec(1500);
      break;

    } else if (getButtonPress(buttonRight)) {
      // Code 2
      displayCenteredTextLine(8, "Running Code 2");
      // Insert Code 2 Here

      int distance = 0;
  // Move forward until an obstacle is detected
  while (true)
  {
    distance = getUSDistance(UltraSensor);
    if (distance < 10)
      break;
    setMotorSpeed(motorLeft,24.99);
    setMotorSpeed(motorRight,24.9999);
  }
  // Stop for 5 seconds
  setMotorSpeed(motorLeft, 0);
  setMotorSpeed(motorRight, 0);
  wait1Msec(5000);
  // Reverse for 3 seconds
  setMotorSpeed(motorLeft, -25);
  setMotorSpeed(motorRight, -25);
  wait1Msec(3000);
  // Stop for 2 seconds
  setMotorSpeed(motorLeft, 0);
  setMotorSpeed(motorRight, 0);
  wait1Msec(2000);
  // Turn for 1420 milliseconds
  setMotorSpeed(motorLeft, -25);
  setMotorSpeed(motorRight, 25);
  wait1Msec(1420);
  // Pause for 2 seconds
  setMotorSpeed(motorLeft, 0);
  setMotorSpeed(motorRight, 0);
  wait1Msec(2000);
  // Move forward until an obstacle is detected
  while (true)
  {
    distance = getUSDistance(UltraSensor);
    if (distance < 65)
      break;
    setMotorSpeed(motorLeft, 25);
    setMotorSpeed(motorRight, 25);
  }
  //pause for 2 secs
  setMotorSpeed(motorLeft, 0);
  setMotorSpeed(motorRight, 0);
  wait1Msec(2000);
  // Turn Left for 780 milliseconds
  setMotorSpeed(motorLeft, -25);
  setMotorSpeed(motorRight, 25);
  wait1Msec(780);
  //Stop for 2 seconds
  setMotorSpeed(motorLeft, 0);
  setMotorSpeed(motorRight, 0);
  wait1Msec(2000);
  // Move forward until an obstacle is detected
  while (true)
  {
    distance = getUSDistance(UltraSensor);
    if (distance < 22)
      break;
    setMotorSpeed(motorLeft, 25);
    setMotorSpeed(motorRight, 25);
  }
  //stop for 2 seconds
  setMotorSpeed(motorLeft, 0);
  setMotorSpeed(motorRight, 0);
  wait1Msec(2000);
  // Turn left for 725 milliseconds
  setMotorSpeed(motorLeft, -25);
  setMotorSpeed(motorRight, 25);
  wait1Msec(740);
  //stop for 2 seconds
  setMotorSpeed(motorLeft, 0);
  setMotorSpeed(motorRight, 0);
  wait1Msec(2000);
   // Move forward for 7600 milliseconds
  setMotorSpeed(motorLeft, 25);
  setMotorSpeed(motorRight, 25);
  wait1Msec(7570);
  //stop for 2 seconds
  setMotorSpeed(motorLeft, 0);
  setMotorSpeed(motorRight, 0);
  wait1Msec(2000);
  // Turn left for 750 milliseconds
  setMotorSpeed(motorLeft, -25);
  setMotorSpeed(motorRight, 25);
  wait1Msec(750);
  //stop for 2 seconds
  setMotorSpeed(motorLeft, 0);
  setMotorSpeed(motorRight, 0);
  wait1Msec(2000);
  // Move forward until an obstacle is detected
  while (true)
  {
    distance = getUSDistance(UltraSensor);
    if (distance < 10)
      break;
    setMotorSpeed(motorLeft, 20);
    setMotorSpeed(motorRight, 20);
  }
  // Stop for 5 second
  setMotorSpeed(motorLeft, 0);
  setMotorSpeed(motorRight, 0);
  wait1Msec(5000);
  // Turn around for 1450 milliseconds
  setMotorSpeed(motorLeft, -25);
  setMotorSpeed(motorRight, 25);
  wait1Msec(1450);
  //stop for 2 seconds
  setMotorSpeed(motorLeft, 0);
  setMotorSpeed(motorRight, 0);
  wait1Msec(2000);
  // Move forward until an obstacle is detected
  while (true)
  {
    distance = getUSDistance(UltraSensor);
    if (distance < 22)
      break;
    setMotorSpeed(motorLeft, 20);
    setMotorSpeed(motorRight, 20);
  }
// Stop for 2 second
  setMotorSpeed(motorLeft, 0);
  setMotorSpeed(motorRight, 0);
  wait1Msec(2000);
// Turn right for 780 milliseconds
  setMotorSpeed(motorLeft, 25);
  setMotorSpeed(motorRight, -25);
  wait1Msec(780);
// Stop for 2 second
  setMotorSpeed(motorLeft, 0);
  setMotorSpeed(motorRight, 0);
  wait1Msec(2000);
 // Move forward for 7100 milliseconds
  setMotorSpeed(motorLeft, 25);
  setMotorSpeed(motorRight, 25);
  wait1Msec(7550);
// Stop for 2 second
  setMotorSpeed(motorLeft, 0);
  setMotorSpeed(motorRight, 0);
  wait1Msec(2000);
// Turn right for 750 milliseconds
  setMotorSpeed(motorLeft, 25);
  setMotorSpeed(motorRight, -25);
  wait1Msec(750);
// Stop for 2 second
  setMotorSpeed(motorLeft, 0);
  setMotorSpeed(motorRight, 0);
  wait1Msec(2000);
 // Move forward until an obstacle is detected
  while (true)
  {
    distance = getUSDistance(UltraSensor);
    if (distance < 20)
      break;
    setMotorSpeed(motorLeft, 20);
    setMotorSpeed(motorRight, 20);
  }
//stop for 2 seconds
  setMotorSpeed(motorLeft, 0);
  setMotorSpeed(motorRight, 0);
  wait1Msec(2000);
// Turn left for 780 milliseconds
  setMotorSpeed(motorLeft, -25);
  setMotorSpeed(motorRight, 25);
  wait1Msec(780);
// Stop for 2 second
  setMotorSpeed(motorLeft, 0);
  setMotorSpeed(motorRight, 0);
  wait1Msec(2000);
// Move forward until an obstacle is detected
  while (true)
  {
    distance = getUSDistance(UltraSensor);
    if (distance < 10)
      break;
    setMotorSpeed(motorLeft, 25);
    setMotorSpeed(motorRight, 25);
  }
  //stop for 2 seconds
  setMotorSpeed(motorLeft, 0);
  setMotorSpeed(motorRight, 0);
  wait1Msec(2000);
  // Turn for 1400 milliseconds
  setMotorSpeed(motorLeft, -25);
  setMotorSpeed(motorRight, 25);
  wait1Msec(1400);

      break;
    } else if (getButtonPress(buttonDown)) {
      // Code 3
      displayCenteredTextLine(8, "Running Code 3");
      // Insert Code 3 Here

        int distance = 0;
  // Move forward until an obstacle is detected
  while (true)
  {
    distance = getUSDistance(UltraSensor);
    if (distance < 10)
      break;
    setMotorSpeed(motorLeft,25.2);
    setMotorSpeed(motorRight,25);
  }
  // Stop for 5 seconds
  setMotorSpeed(motorLeft, 0);
  setMotorSpeed(motorRight, 0);
  wait1Msec(5000);
  // Reverse for 3 seconds
  setMotorSpeed(motorLeft, -25);
  setMotorSpeed(motorRight, -25);
  wait1Msec(3000);
  // Stop for 2 seconds
  setMotorSpeed(motorLeft, 0);
  setMotorSpeed(motorRight, 0);
  wait1Msec(2000);
  // Turn for 1400 milliseconds
  setMotorSpeed(motorLeft, -25);
  setMotorSpeed(motorRight, 25);
  wait1Msec(1450);
  // Pause for 2 seconds
  setMotorSpeed(motorLeft, 0);
  setMotorSpeed(motorRight, 0);
  wait1Msec(2000);
  // Move forward until an obstacle is detected
  while (true)
  {
    distance = getUSDistance(UltraSensor);
    if (distance < 65)
      break;
    setMotorSpeed(motorLeft, 25);
    setMotorSpeed(motorRight, 25);
  }
  //pause for 2 secs
  setMotorSpeed(motorLeft, 0);
  setMotorSpeed(motorRight, 0);
  wait1Msec(2000);
  // Turn Left for 760 milliseconds
  setMotorSpeed(motorLeft, -25);
  setMotorSpeed(motorRight, 25);
  wait1Msec(760);
  //Stop for 2 seconds
  setMotorSpeed(motorLeft, 0);
  setMotorSpeed(motorRight, 0);
  wait1Msec(2000);
  // Move forward until an obstacle is detected
  while (true)
  {
    distance = getUSDistance(UltraSensor);
    if (distance < 22)
      break;
    setMotorSpeed(motorLeft, 25);
    setMotorSpeed(motorRight, 25);
  }
  //stop for 2 seconds
  setMotorSpeed(motorLeft, 0);
  setMotorSpeed(motorRight, 0);
  wait1Msec(2000);
  // Turn left for 755 milliseconds
  setMotorSpeed(motorLeft, -25);
  setMotorSpeed(motorRight, 25);
  wait1Msec(755);
  //stop for 2 seconds
  setMotorSpeed(motorLeft, 0);
  setMotorSpeed(motorRight, 0);
  wait1Msec(2000);
   // Move forward for 12000 milliseconds
  setMotorSpeed(motorLeft, 25);
  setMotorSpeed(motorRight, 25);
  wait1Msec(11850);
  //stop for 2 seconds
  setMotorSpeed(motorLeft, 0);
  setMotorSpeed(motorRight, 0);
  wait1Msec(2000);
  // Turn left for 750 milliseconds
  setMotorSpeed(motorLeft, -25);
  setMotorSpeed(motorRight, 25);
  wait1Msec(750);
  //stop for 2 seconds
  setMotorSpeed(motorLeft, 0);
  setMotorSpeed(motorRight, 0);
  wait1Msec(2000);
  // Move forward until an obstacle is detected
  while (true)
  {
    distance = getUSDistance(UltraSensor);
    if (distance < 10)
      break;
    setMotorSpeed(motorLeft, 20);
    setMotorSpeed(motorRight, 20);
  }
  // Stop for 5 second
  setMotorSpeed(motorLeft, 0);
  setMotorSpeed(motorRight, 0);
  wait1Msec(5000);
  // Turn around for 1450 milliseconds
  setMotorSpeed(motorLeft, -25);
  setMotorSpeed(motorRight, 25);
  wait1Msec(1450);
  //stop for 2 seconds
  setMotorSpeed(motorLeft, 0);
  setMotorSpeed(motorRight, 0);
  wait1Msec(2000);
  // Move forward until an obstacle is detected
  while (true)
  {
    distance = getUSDistance(UltraSensor);
    if (distance < 22)
      break;
    setMotorSpeed(motorLeft, 20);
    setMotorSpeed(motorRight, 20);
  }
// Stop for 2 second
  setMotorSpeed(motorLeft, 0);
  setMotorSpeed(motorRight, 0);
  wait1Msec(2000);
// Turn right for 700 milliseconds
  setMotorSpeed(motorLeft, 25);
  setMotorSpeed(motorRight, -25);
  wait1Msec(720);
// Stop for 2 second
  setMotorSpeed(motorLeft, 0);
  setMotorSpeed(motorRight, 0);
  wait1Msec(2000);
 // Move forward for 11450 milliseconds
  setMotorSpeed(motorLeft, 25);
  setMotorSpeed(motorRight, 25);
  wait1Msec(11450);
// Stop for 2 second
  setMotorSpeed(motorLeft, 0);
  setMotorSpeed(motorRight, 0);
  wait1Msec(2000);
// Turn right for 750 milliseconds
  setMotorSpeed(motorLeft, 25);
  setMotorSpeed(motorRight, -25);
  wait1Msec(750);
// Stop for 2 second
  setMotorSpeed(motorLeft, 0);
  setMotorSpeed(motorRight, 0);
  wait1Msec(2000);
 // Move forward until an obstacle is detected
  while (true)
  {
    distance = getUSDistance(UltraSensor);
    if (distance < 20)
      break;
    setMotorSpeed(motorLeft, 20);
    setMotorSpeed(motorRight, 20);
  }
//stop for 2 seconds
  setMotorSpeed(motorLeft, 0);
  setMotorSpeed(motorRight, 0);
  wait1Msec(2000);
// Turn left for 760 milliseconds
  setMotorSpeed(motorLeft, -25);
  setMotorSpeed(motorRight, 25);
  wait1Msec(760);
// Stop for 2 second
  setMotorSpeed(motorLeft, 0);
  setMotorSpeed(motorRight, 0);
  wait1Msec(2000);
// Move forward until an obstacle is detected
  while (true)
  {
    distance = getUSDistance(UltraSensor);
    if (distance < 10)
      break;
    setMotorSpeed(motorLeft, 25);
    setMotorSpeed(motorRight, 25);
  }
  //stop for 2 seconds
  setMotorSpeed(motorLeft, 0);
  setMotorSpeed(motorRight, 0);
  wait1Msec(2000);
  // Turn for 1400 milliseconds
  setMotorSpeed(motorLeft, -25);
  setMotorSpeed(motorRight, 25);
  wait1Msec(1400);

      break;
    }
  }
}
